stages:
  Load Data:
    cmd: python src/data_preprocessor.py
    deps:
      - src/data_preprocessor.py
    outs:
      - data/X_train.npy
      - data/Y_train.npy
      - data/X_test.npy
      - data/Y_test.npy
  Train Model:
    cmd: python src/train.py
    deps:
      - src/train.py
    outs:
      - data/train_history
  Evaluate trained Model:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
    outs:
      - Model_Evaluation_Report

